### ISSUE TITLE
Do you have this dataset?

### ISSUE THREAD

**Issue by kopyl** [asg017/sqlite-parquet#1]
Hey. Is there any chance you have this dataset cached locally and can send it to me?

https://huggingface.co/datasets/ChristophSchuhmann/improved_aesthetics_6plus

I'm going to train miniSDXL (like lambdalabs/miniSD-diffusers, but for SDXL) and need the exact same dataset which was used here... 

Just close and delete this issue please if you can't help me.

**Comment by asg017** [comment]
I do not, sorry. Though this might be why it's hard to find: https://www.theverge.com/2023/12/20/24009418/generative-ai-image-laion-csam-google-stability-stanford

**Comment by kopyl** [comment]
@asg017 thank you very much for your response. Yeah, i've heard about that. But i'd be more than okay if someone who can share it with me would remove that content before sending to me :)
